# Generated by Django 4.2.4 on 2025-03-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
