# Generated by Django 4.2.4 on 2025-03-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='firebase_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
